sudo: false
language: python
matrix:
  include:
    - python: "2.7"
      dist: trusty
    - python: "3.4"
      dist: trusty
    - python: "3.5"
      dist: trusty
    - python: "3.6"
      dist: trusty
    - python: "3.7"
      dist: xenial
      sudo: true
    - python: "3.7-dev"
      dist: xenial
      sudo: true
install: pip install tox-travis
script: tox